In [1]:
import numpy as np
import re

#INPUT_FN = "input_test.txt"
INPUT_FN = "input.txt"

with open(INPUT_FN) as f:
    lines = [l.rstrip() for l in f]

In [2]:
# first line development

values = [int(s) for s in lines[0].split(' ')]

In [3]:
values

[10,
 20,
 37,
 71,
 136,
 258,
 493,
 972,
 2001,
 4255,
 9116,
 19216,
 39257,
 77191,
 145854,
 265159,
 464964,
 788742,
 1298191,
 2078933,
 3247462]

In [4]:
# Build up pyramid of differences down to zeros
diffs_pyr=[values]

while True:
    row = diffs_pyr[-1] # last row
    new_row = []
    is_all_zeros=True
    for i in range(len(row)-1):
        val=row[i+1]-row[i]
        new_row.append(val)
        if val!=0:
            is_all_zeros=False
    
    diffs_pyr.append(new_row)
    if is_all_zeros:
        break

In [5]:
diffs_pyr

[[10,
  20,
  37,
  71,
  136,
  258,
  493,
  972,
  2001,
  4255,
  9116,
  19216,
  39257,
  77191,
  145854,
  265159,
  464964,
  788742,
  1298191,
  2078933,
  3247462],
 [10,
  17,
  34,
  65,
  122,
  235,
  479,
  1029,
  2254,
  4861,
  10100,
  20041,
  37934,
  68663,
  119305,
  199805,
  323778,
  509449,
  780742,
  1168529],
 [7,
  17,
  31,
  57,
  113,
  244,
  550,
  1225,
  2607,
  5239,
  9941,
  17893,
  30729,
  50642,
  80500,
  123973,
  185671,
  271293,
  387787],
 [10,
  14,
  26,
  56,
  131,
  306,
  675,
  1382,
  2632,
  4702,
  7952,
  12836,
  19913,
  29858,
  43473,
  61698,
  85622,
  116494],
 [4,
  12,
  30,
  75,
  175,
  369,
  707,
  1250,
  2070,
  3250,
  4884,
  7077,
  9945,
  13615,
  18225,
  23924,
  30872],
 [8,
  18,
  45,
  100,
  194,
  338,
  543,
  820,
  1180,
  1634,
  2193,
  2868,
  3670,
  4610,
  5699,
  6948],
 [10, 27, 55, 94, 144, 205, 277, 360, 454, 559, 675, 802, 940, 1089, 1249],
 [17, 28, 39, 50, 61, 72, 83, 94, 105, 116, 127, 138, 149, 160],
 [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

Now, pretend to add zero to last and go backwards, to get new values

$a_{n+1} = b_n + a_n $

In [6]:
new_val_below = 0

new_vals = []

for i in range(len(diffs_pyr)-2, -1,-1): # start from previous to last row and go backwards
    row = diffs_pyr[i]
    print(row)

    new_val_above = row[-1]+new_val_below
    new_vals.append(new_val_above)

    new_val_below= new_val_above #next iteration

print(new_val_above)
print(new_vals)

[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11]
[17, 28, 39, 50, 61, 72, 83, 94, 105, 116, 127, 138, 149, 160]
[10, 27, 55, 94, 144, 205, 277, 360, 454, 559, 675, 802, 940, 1089, 1249]
[8, 18, 45, 100, 194, 338, 543, 820, 1180, 1634, 2193, 2868, 3670, 4610, 5699, 6948]
[4, 12, 30, 75, 175, 369, 707, 1250, 2070, 3250, 4884, 7077, 9945, 13615, 18225, 23924, 30872]
[10, 14, 26, 56, 131, 306, 675, 1382, 2632, 4702, 7952, 12836, 19913, 29858, 43473, 61698, 85622, 116494]
[7, 17, 31, 57, 113, 244, 550, 1225, 2607, 5239, 9941, 17893, 30729, 50642, 80500, 123973, 185671, 271293, 387787]
[10, 17, 34, 65, 122, 235, 479, 1029, 2254, 4861, 10100, 20041, 37934, 68663, 119305, 199805, 323778, 509449, 780742, 1168529]
[10, 20, 37, 71, 136, 258, 493, 972, 2001, 4255, 9116, 19216, 39257, 77191, 145854, 265159, 464964, 788742, 1298191, 2078933, 3247462]
4959512
[11, 171, 1420, 8368, 39240, 155734, 543521, 1712050, 4959512]

OK

Execute the same for all lines

In [7]:
new_vals = []
for sline in lines:
    values = [int(s) for s in sline.split(' ')]

    # Build up pyramid of differences down to zeros
    diffs_pyr=[values]
    while True:
        row = diffs_pyr[-1] # last row
        new_row = []
        is_all_zeros=True
        for i in range(len(row)-1):
            val=row[i+1]-row[i]
            new_row.append(val)
            if val!=0:
                is_all_zeros=False
        
        diffs_pyr.append(new_row)
        if is_all_zeros:
            break
    
    new_val_below = 0

    for i in range(len(diffs_pyr)-2, -1,-1): # start from previous to last row and go backwards
        row = diffs_pyr[i]
        #print(row)

        new_val_above = row[-1]+new_val_below

        new_val_below= new_val_above #next iteration

    print(new_val_above)

    new_vals.append(new_val_above)

4959512
415945
143545
-401653
-75
2148050
291105
20448529
329527
8581868
4248605
344758
34132944
1085
17072078
226
10671426
35470263
28667085
16439955
13368409
731833
207
-711911
-17
25281247
20064211
16574
9733
24708134
20933357
24154452
6269257
1974788
12445357
260854
14351213
210428
3832263
14944073
13506058
28654275
15040512
20581893
1693300
22204740
11868922
6420155
196
2329
13668862
-4794
20085519
17350845
-1861
1098
291949
1103988
107192
19720028
155260
9097294
983049
2852729
20273545
6389055
26259787
5310886
14052313
19813
13825952
13537077
74907
31642617
8201548
22602
24240757
9190
13324573
147
8553122
20147440
12960604
7076187
9200155
60923
-6863
13201281
6814944
1371
3875537
28490769
25280291
2872
150641
23496696
106807
1183853
-100
478111
52163
274
4865012
1493
16980187
2974
37931309
2804256
13373803
7795564
40329
14438481
-38
23090024
14684
15503
-4608
4101975
87394
889216
58271
11245597
-6197
1415046
25486899
-32773
-5224398
21907208
20085190
21451196
23967018
14409893
16591
25505342
30916618
9995023
316
18833990
12495752
15216408
4166050
18164083
31328672
15100157
3138107
-2601
12957172
12419393
7462020
20692571
17339541
1658373
18571638
2012
4084677
11238859
10049246
-127281
6251952
-1047
35386463
10921471
21476561
10170781
44335
16616779
18080300
49674
5362
23009379
10456465
-2647781
17869656
51591
96399
2967699
27218626
12407442
2817127
5708385
550840
25577091
15531638
25192856
216432
17942388
26527848
318087
538744
-5457
19232200
2615770
10989670
-67
5166038
4280
916961
236685
7304114
2413520

In [8]:
new_vals

[4959512,
 415945,
 143545,
 -401653,
 -75,
 2148050,
 291105,
 20448529,
 329527,
 8581868,
 4248605,
 344758,
 34132944,
 1085,
 17072078,
 226,
 10671426,
 35470263,
 28667085,
 16439955,
 13368409,
 731833,
 207,
 -711911,
 -17,
 25281247,
 20064211,
 16574,
 9733,
 24708134,
 20933357,
 24154452,
 6269257,
 1974788,
 12445357,
 260854,
 14351213,
 210428,
 3832263,
 14944073,
 13506058,
 28654275,
 15040512,
 20581893,
 1693300,
 22204740,
 11868922,
 6420155,
 196,
 2329,
 13668862,
 -4794,
 20085519,
 17350845,
 -1861,
 1098,
 291949,
 1103988,
 107192,
 19720028,
 155260,
 9097294,
 983049,
 2852729,
 20273545,
 6389055,
 26259787,
 5310886,
 14052313,
 19813,
 13825952,
 13537077,
 74907,
 31642617,
 8201548,
 22602,
 24240757,
 9190,
 13324573,
 147,
 8553122,
 20147440,
 12960604,
 7076187,
 9200155,
 60923,
 -6863,
 13201281,
 6814944,
 1371,
 3875537,
 28490769,
 25280291,
 2872,
 150641,
 23496696,
 106807,
 1183853,
 -100,
 478111,
 52163,
 274,
 4865012,
 1493,
 16980187,
 2974,
 37931309,
 2804256,
 13373803,
 7795564,
 40329,
 14438481,
 -38,
 23090024,
 14684,
 15503,
 -4608,
 4101975,
 87394,
 889216,
 58271,
 11245597,
 -6197,
 1415046,
 25486899,
 -32773,
 -5224398,
 21907208,
 20085190,
 21451196,
 23967018,
 14409893,
 16591,
 25505342,
 30916618,
 9995023,
 316,
 18833990,
 12495752,
 15216408,
 4166050,
 18164083,
 31328672,
 15100157,
 3138107,
 -2601,
 12957172,
 12419393,
 7462020,
 20692571,
 17339541,
 1658373,
 18571638,
 2012,
 4084677,
 11238859,
 10049246,
 -127281,
 6251952,
 -1047,
 35386463,
 10921471,
 21476561,
 10170781,
 44335,
 16616779,
 18080300,
 49674,
 5362,
 23009379,
 10456465,
 -2647781,
 17869656,
 51591,
 96399,
 2967699,
 27218626,
 12407442,
 2817127,
 5708385,
 550840,
 25577091,
 15531638,
 25192856,
 216432,
 17942388,
 26527848,
 318087,
 538744,
 -5457,
 19232200,
 2615770,
 10989670,
 -67,
 5166038,
 4280,
 916961,
 236685,
 7304114,
 2413520]

In [9]:
sum(new_vals)

1853145119

# Part 2
Similar but adding elements to the start rather than end

Similar loop but different formula and elements to use

In [11]:
new_vals = []
for sline in lines:
    values = [int(s) for s in sline.split(' ')]

    # Build up pyramid of differences down to zeros
    diffs_pyr=[values]
    while True:
        row = diffs_pyr[-1] # last row
        new_row = []
        is_all_zeros=True
        for i in range(len(row)-1):
            val=row[i+1]-row[i]
            new_row.append(val)
            if val!=0:
                is_all_zeros=False
        
        diffs_pyr.append(new_row)
        if is_all_zeros:
            break
    
    new_val_below = 0

    for i in range(len(diffs_pyr)-2, -1,-1): # start from previous to last row and go backwards
        row = diffs_pyr[i]
        #print(row)

        #first element and subtracts to value below
        new_val_above = row[0]- new_val_below

        new_val_below= new_val_above #next iteration

    #print(new_val_above)

    new_vals.append(new_val_above)

In [12]:
new_vals

[-3,
 13,
 6,
 1,
 13,
 14,
 1,
 -2,
 0,
 9,
 -2,
 7,
 13,
 -4,
 4,
 6,
 12,
 2,
 10,
 -1,
 12,
 14,
 9,
 -3,
 5,
 -2,
 12,
 8,
 -2,
 2,
 -5,
 12,
 4,
 13,
 12,
 11,
 -4,
 9,
 6,
 2,
 1,
 -1,
 -1,
 10,
 15,
 10,
 -1,
 -4,
 -2,
 -3,
 9,
 -3,
 -3,
 14,
 9,
 9,
 -2,
 6,
 8,
 7,
 -5,
 -3,
 12,
 10,
 12,
 2,
 13,
 9,
 2,
 2,
 3,
 14,
 -3,
 15,
 3,
 -3,
 2,
 5,
 9,
 15,
 12,
 -2,
 8,
 -3,
 5,
 5,
 12,
 5,
 15,
 -4,
 6,
 9,
 3,
 1,
 -4,
 6,
 -3,
 0,
 10,
 -4,
 1,
 10,
 -2,
 -3,
 4,
 4,
 7,
 4,
 -2,
 -4,
 14,
 1,
 6,
 11,
 10,
 4,
 12,
 9,
 -1,
 -2,
 4,
 11,
 7,
 -5,
 0,
 -4,
 -4,
 14,
 13,
 4,
 15,
 13,
 3,
 8,
 7,
 5,
 8,
 12,
 4,
 -2,
 -2,
 9,
 -5,
 13,
 5,
 6,
 -3,
 -3,
 15,
 14,
 3,
 13,
 3,
 10,
 3,
 15,
 11,
 0,
 6,
 -2,
 7,
 11,
 -5,
 13,
 5,
 -5,
 1,
 -2,
 5,
 1,
 -3,
 13,
 11,
 1,
 -5,
 9,
 15,
 1,
 5,
 12,
 4,
 -2,
 4,
 5,
 7,
 10,
 10,
 11,
 -3,
 -1,
 0,
 3,
 -1,
 -1,
 -5,
 1,
 1,
 -2,
 3,
 -1]

In [13]:
sum(new_vals)

923